name: Publish
on:
  schedule:
    - cron: "* * * * *" # every minute
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Gatsby Cloud
        env:
          BUILD_HOOK_URL: ${{ secrets.BUILD_HOOK_URL }}
        run: curl -L -X POST "${BUILD_HOOK_URL}" -d "{}"