name: Publish
on:
  schedule:
    - cron: "*/1 * * * *" # every minute, y'all
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Re-build
        env:
          BUILD_HOOK_URL: ${{ secrets.BUILD_HOOK_URL }}
        run: curl -L -X POST "${BUILD_HOOK_URL}" -d "{}" 
